name: Check for forbidden files

on:
  push:
  pull_request:

jobs:
  check-forbidden:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check forbidden files
        run: |
          forbidden=(
            ".env"
            ".venv"
            "data"
            "quiz_users.csv"
            "bookings.csv"
            "coupons_generated.csv"
            "facts_template.csv"
            "tmp_menu_cache"
            "*.log"
          )
          found=0
          for f in "${forbidden[@]}"; do
            if ls $f 1>/dev/null 2>&1; then
              echo "❌ Forbidden file or folder found: $f"
              found=1
            fi
          done
          if [ $found -eq 1 ]; then
            echo "Commit rejected due to forbidden files."
            exit 1
          fi
          echo "✅ No forbidden files detected."
