name: Mirror to public

on:
  push:
    branches: [ main ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Strip private files
        run: |
          rm -rf .venv data .env tmp_menu_cache *.log || true
          rm -f quiz_users.csv bookings.csv coupons_generated.csv facts_template.csv || true

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.MIRROR_SSH_KEY }}

      - name: Push to public mirror
        run: |
          git config user.name "mirror-bot"
          git config user.email "mirror-bot@users.noreply.github.com"
          git checkout -B main
          git add -A
          git commit -m "mirror: ${GITHUB_SHA}" || echo "nothing to commit"
          git push -f git@github.com:malekuloman-ship-it/poddonbot-mirror.git main

